# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.cwMain = QtWidgets.QWidget(MainWindow)
        self.cwMain.setObjectName("cwMain")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.cwMain)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hlSlider = QtWidgets.QHBoxLayout()
        self.hlSlider.setObjectName("hlSlider")
        self.hslFrame = QtWidgets.QSlider(self.cwMain)
        self.hslFrame.setOrientation(QtCore.Qt.Horizontal)
        self.hslFrame.setObjectName("hslFrame")
        self.hlSlider.addWidget(self.hslFrame)
        self.sbxFrame = QtWidgets.QSpinBox(self.cwMain)
        self.sbxFrame.setObjectName("sbxFrame")
        self.hlSlider.addWidget(self.sbxFrame)
        self.lblFrames = QtWidgets.QLabel(self.cwMain)
        self.lblFrames.setObjectName("lblFrames")
        self.hlSlider.addWidget(self.lblFrames)
        self.verticalLayout_2.addLayout(self.hlSlider)
        self.hlSelection = QtWidgets.QHBoxLayout()
        self.hlSelection.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.hlSelection.setObjectName("hlSelection")
        self.btnAddSegment = QtWidgets.QPushButton(self.cwMain)
        self.btnAddSegment.setObjectName("btnAddSegment")
        self.hlSelection.addWidget(self.btnAddSegment)
        self.btnDelSegment = QtWidgets.QPushButton(self.cwMain)
        self.btnDelSegment.setObjectName("btnDelSegment")
        self.hlSelection.addWidget(self.btnDelSegment)
        self.line = QtWidgets.QFrame(self.cwMain)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hlSelection.addWidget(self.line)
        self.lblSegmentStart = QtWidgets.QLabel(self.cwMain)
        self.lblSegmentStart.setObjectName("lblSegmentStart")
        self.hlSelection.addWidget(self.lblSegmentStart)
        self.sbxStartFrame = QtWidgets.QSpinBox(self.cwMain)
        self.sbxStartFrame.setObjectName("sbxStartFrame")
        self.hlSelection.addWidget(self.sbxStartFrame)
        self.line_2 = QtWidgets.QFrame(self.cwMain)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.hlSelection.addWidget(self.line_2)
        self.lblSegmentEnd = QtWidgets.QLabel(self.cwMain)
        self.lblSegmentEnd.setObjectName("lblSegmentEnd")
        self.hlSelection.addWidget(self.lblSegmentEnd)
        self.sbxEndFrame = QtWidgets.QSpinBox(self.cwMain)
        self.sbxEndFrame.setObjectName("sbxEndFrame")
        self.hlSelection.addWidget(self.sbxEndFrame)
        self.verticalLayout_2.addLayout(self.hlSelection)
        self.hlFrame = QtWidgets.QHBoxLayout()
        self.hlFrame.setObjectName("hlFrame")
        self.gvFrame = QtWidgets.QGraphicsView(self.cwMain)
        self.gvFrame.setObjectName("gvFrame")
        self.hlFrame.addWidget(self.gvFrame)
        self.verticalLayout_2.addLayout(self.hlFrame)
        self.line_4 = QtWidgets.QFrame(self.cwMain)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.lblCyrillic = QtWidgets.QLabel(self.cwMain)
        self.lblCyrillic.setObjectName("lblCyrillic")
        self.verticalLayout_2.addWidget(self.lblCyrillic)
        self.hlCyrillic = QtWidgets.QHBoxLayout()
        self.hlCyrillic.setObjectName("hlCyrillic")
        self.texCyrillic = QtWidgets.QTextEdit(self.cwMain)
        self.texCyrillic.setObjectName("texCyrillic")
        self.hlCyrillic.addWidget(self.texCyrillic)
        self.vlCyrillicButtons = QtWidgets.QVBoxLayout()
        self.vlCyrillicButtons.setObjectName("vlCyrillicButtons")
        self.btnOcr = QtWidgets.QPushButton(self.cwMain)
        self.btnOcr.setObjectName("btnOcr")
        self.vlCyrillicButtons.addWidget(self.btnOcr)
        self.line_5 = QtWidgets.QFrame(self.cwMain)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.vlCyrillicButtons.addWidget(self.line_5)
        self.btnCyrillicEdit = QtWidgets.QPushButton(self.cwMain)
        self.btnCyrillicEdit.setObjectName("btnCyrillicEdit")
        self.vlCyrillicButtons.addWidget(self.btnCyrillicEdit)
        self.hlCyrillic.addLayout(self.vlCyrillicButtons)
        self.tableView = QtWidgets.QTableView(self.cwMain)
        self.tableView.setObjectName("tableView")
        self.hlCyrillic.addWidget(self.tableView)
        self.verticalLayout_2.addLayout(self.hlCyrillic)
        self.line_3 = QtWidgets.QFrame(self.cwMain)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.lblEnglish = QtWidgets.QLabel(self.cwMain)
        self.lblEnglish.setObjectName("lblEnglish")
        self.verticalLayout_2.addWidget(self.lblEnglish)
        self.hlEnglish = QtWidgets.QHBoxLayout()
        self.hlEnglish.setObjectName("hlEnglish")
        self.texEnglish = QtWidgets.QTextEdit(self.cwMain)
        self.texEnglish.setObjectName("texEnglish")
        self.hlEnglish.addWidget(self.texEnglish)
        self.vlEnglishButtons = QtWidgets.QVBoxLayout()
        self.vlEnglishButtons.setObjectName("vlEnglishButtons")
        self.btnTranslate = QtWidgets.QPushButton(self.cwMain)
        self.btnTranslate.setObjectName("btnTranslate")
        self.vlEnglishButtons.addWidget(self.btnTranslate)
        self.line_6 = QtWidgets.QFrame(self.cwMain)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.vlEnglishButtons.addWidget(self.line_6)
        self.btnEnglishEdit = QtWidgets.QPushButton(self.cwMain)
        self.btnEnglishEdit.setObjectName("btnEnglishEdit")
        self.vlEnglishButtons.addWidget(self.btnEnglishEdit)
        self.hlEnglish.addLayout(self.vlEnglishButtons)
        self.verticalLayout_2.addLayout(self.hlEnglish)
        MainWindow.setCentralWidget(self.cwMain)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew_Project = QtWidgets.QAction(MainWindow)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.actionLoad_Project = QtWidgets.QAction(MainWindow)
        self.actionLoad_Project.setObjectName("actionLoad_Project")
        self.actionSave_Project = QtWidgets.QAction(MainWindow)
        self.actionSave_Project.setObjectName("actionSave_Project")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionIdentify_Segments = QtWidgets.QAction(MainWindow)
        self.actionIdentify_Segments.setObjectName("actionIdentify_Segments")
        self.actionOCR_All = QtWidgets.QAction(MainWindow)
        self.actionOCR_All.setObjectName("actionOCR_All")
        self.actionTranslate_All = QtWidgets.QAction(MainWindow)
        self.actionTranslate_All.setObjectName("actionTranslate_All")
        self.menuMain.addAction(self.actionNew_Project)
        self.menuMain.addAction(self.actionLoad_Project)
        self.menuMain.addAction(self.actionSave_Project)
        self.menuMain.addSeparator()
        self.menuMain.addAction(self.actionClose)
        self.menubar.addAction(self.menuMain.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblFrames.setText(_translate("MainWindow", "/ 30000"))
        self.btnAddSegment.setText(_translate("MainWindow", "Add Segment"))
        self.btnDelSegment.setText(_translate("MainWindow", "Delete Segment"))
        self.lblSegmentStart.setText(_translate("MainWindow", "Segment Start"))
        self.lblSegmentEnd.setText(_translate("MainWindow", "Segment End"))
        self.lblCyrillic.setText(_translate("MainWindow", "Cyrillic"))
        self.btnOcr.setText(_translate("MainWindow", "OCR"))
        self.btnCyrillicEdit.setText(_translate("MainWindow", "Edit..."))
        self.lblEnglish.setText(_translate("MainWindow", "English"))
        self.btnTranslate.setText(_translate("MainWindow", "Translate"))
        self.btnEnglishEdit.setText(_translate("MainWindow", "Edit..."))
        self.menuMain.setTitle(_translate("MainWindow", "Main"))
        self.actionNew_Project.setText(_translate("MainWindow", "New Project..."))
        self.actionLoad_Project.setText(_translate("MainWindow", "Load Project..."))
        self.actionSave_Project.setText(_translate("MainWindow", "Save Project..."))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionIdentify_Segments.setText(_translate("MainWindow", "Identify Segments"))
        self.actionOCR_All.setText(_translate("MainWindow", "OCR All"))
        self.actionTranslate_All.setText(_translate("MainWindow", "Translate All"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

